@startuml diagrama_venta

skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rectangle
skinparam linetype ortho

package "Adaptadores (Exterior)" {
    class InMemoryVentaRepository
    class InMemoryProductoRepository
}

package "Núcleo de la Aplicación" {
    package "Puertos (Interfaces)" {
        interface VentaRepository
        interface ConfirmarVentaUseCase
    }

    package "Aplicación (Servicios y Casos de Uso)" {
        class VentaFacade <<Facade>>
        class ConfirmarVentaService
        
        interface PoliticaDescuento <<Strategy>>
        class DescuentoEstudiante
        class SinDescuento
        
        class ActualizadorInventario
        class BitacoraVenta
    }

    package "Dominio (Reglas de Negocio)" {
        class Venta
        class Producto
        
        class VentaFactory <<Factory>>
        class DetalleVentaFactory <<Factory>>
        
        interface VentaObserver <<Observer>>
    }
}

' Implementación de Adaptadores
VentaRepository <|.. InMemoryVentaRepository
ConfirmarVentaUseCase <|.. ConfirmarVentaService

' Relaciones del Patrón Facade (El Orquestador)
VentaFacade --> VentaFactory : Usa
VentaFacade --> DetalleVentaFactory : Usa
VentaFacade --> VentaRepository : Guarda
VentaFacade --> ConfirmarVentaService : Delega
VentaFacade ..> PoliticaDescuento : Aplica descuento

' Relaciones del Patrón Strategy
PoliticaDescuento <|.. DescuentoEstudiante
PoliticaDescuento <|.. SinDescuento

' Relaciones del Patrón Observer
VentaObserver <|.. ActualizadorInventario
VentaObserver <|.. BitacoraVenta
ConfirmarVentaService o--> VentaObserver : Notifica lista de observadores

' Relaciones del Patrón Factory
VentaFactory ..> Venta : Instancia objeto válido
DetalleVentaFactory ..> Producto : Vincula

@enduml
